(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const DAY_NAMES=['星期一','星期二','星期三','星期四','星期五','星期六','星期日'];
const DAY_SHORT=['一','二','三','四','五','六','日'];
const DEFAULT_TIMES=[['第一節','08:40','09:20'],['第二節','09:30','10:10'],['第三節','10:30','11:10'],['第四節','11:20','12:00'],['第五節','13:30','14:10'],['第六節','14:20','15:00'],['第七節','15:20','16:00'],['第八節','16:10','16:50'],['第九節','17:00','17:40']];
const TEMPLATES=[
['strawberry','草莓甜點店','01-strawberry-dessert-shop.png'],['rainbow','夢幻彩虹天空','02-rainbow-sky.png'],['castle','紫色童話城堡','03-purple-castle.png'],['dinosaur','恐龍森林探險','04-dinosaur-forest.png'],['ocean','海洋水族館','05-ocean-aquarium.png'],['car','小汽車城市旅行','06-city-car.png'],['donut','甜甜圈烘焙屋','07-donut-bakery.png'],['animals','花園小動物','08-garden-animals.png'],['space','星空火箭旅行','09-space-rocket.png'],['stationery','清新文具樂園','10-stationery-land.png']
];
const SOLIDS=[['macaron-pink','馬卡龍粉','#fbdce8'],['macaron-yellow','馬卡龍黃','#fff1bd'],['macaron-orange','馬卡龍橘','#f9dfc8'],['macaron-green','馬卡龍綠','#dcefd9'],['macaron-blue','馬卡龍藍','#dcecf6'],['macaron-purple','馬卡龍紫','#e9ddf5'],['morandi-gray','莫蘭迪灰','#ded9d6'],['morandi-green','莫蘭迪綠','#ccd8c8'],['morandi-pink','莫蘭迪粉','#dfc8cc'],['morandi-milk-tea','莫蘭迪奶茶','#decfbe'],['morandi-blue','莫蘭迪藍','#c8d4db'],['morandi-purple','莫蘭迪紫','#cec7d7']];
const FONTS=[
{name:'貓啃珠圓體',family:'MaokenZhuyuan, sans-serif'},
{name:'悠哉字體',family:'Yozai, sans-serif'},
{name:'寒蟬童圓體',family:'ChillRound, sans-serif'},
{name:'得意黑',family:'CjkAllseto, sans-serif'},
{name:'Maple Mono Rounded',family:'MapleMonoRounded, sans-serif'},
{name:'辰宇落雁體',family:'ChenYu, sans-serif'},
{name:'思源黑體',family:'"Noto Sans TC", sans-serif'},
{name:'jf open 粉圓',family:'JustfontFenYuan, sans-serif'}
];
const SUBJECT_COLORS=['#f8dce8','#dceafa','#f3e1fb','#def0dc','#fff0c9','#f9dfcd','#dceeea','#e8e1fa','#f7e4dc','#e3edf7','#f4e7b9','#dfe9ce'];
const S={days:5,periodCount:7,clothing:true,morning:true,lunch:true,after:false,showTime:true,format:'a4',font:0,fontScale:1,textColor:'#4b3b52',backgroundMode:'template',template:'strawberry',solid:'macaron-pink',gradient:false,selectedDay:0,courses:{},clothingData:Array(7).fill(''),times:DEFAULT_TIMES.map(v=>[...v]),editingKey:null,images:new Map()};
const canvas=$('#timetableCanvas'),ctx=canvas.getContext('2d');

function rowDefs(){const rows=[];if(S.clothing)rows.push({key:'clothing',label:'服裝',time:''});if(S.morning)rows.push({key:'morning',label:'早自習',time:'08:00～08:40'});for(let i=0;i<S.periodCount;i++){const t=S.times[i];rows.push({key:`p${i}`,label:t[0],time:`${t[1]}～${t[2]}`});if(i===3&&S.lunch)rows.push({key:'lunch',label:'午休',time:'12:00～13:20',merged:true})}if(S.after)rows.push({key:'after',label:'課後時段',time:'16:10～17:30'});return rows}
function cellKey(rowKey,day){return `${rowKey}-${day}`}
function getCell(rowKey,day){if(rowKey==='clothing')return {subject:S.clothingData[day]||'',teacher:'',room:''};if(rowKey==='lunch')return {subject:S.courses.lunch?.subject||'午休',teacher:'',room:''};return S.courses[cellKey(rowKey,day)]||{subject:'',teacher:'',room:''}}
function setCell(rowKey,day,data){if(rowKey==='clothing')S.clothingData[day]=data.subject||'';else if(rowKey==='lunch')S.courses.lunch={subject:data.subject||'午休'};else S.courses[cellKey(rowKey,day)]={subject:data.subject||'',teacher:data.teacher||'',room:data.room||''}}
function subjectColor(subject){if(!subject)return '#ffffffcc';let h=0;for(const c of subject)h=(h*31+c.charCodeAt(0))>>>0;return SUBJECT_COLORS[h%SUBJECT_COLORS.length]}

function renderDayTabs(){const el=$('#dayTabs');el.innerHTML=DAY_SHORT.slice(0,S.days).map((d,i)=>`<button type="button" class="${i===S.selectedDay?'active':''}" data-mobile-day="${i}">${d}</button>`).join('')}
function renderCourseEditor(){const rows=rowDefs(),cols=`105px repeat(${S.days}, minmax(105px,1fr))`;let html=`<div class="edit-grid mobile-mode" style="grid-template-columns:${cols}"><div class="edit-cell header corner">節次／星期</div>`;for(let d=0;d<S.days;d++)html+=`<div class="edit-cell header">${DAY_NAMES[d]}</div>`;
for(const row of rows){html+=`<div class="mobile-row"><div class="edit-cell label">${row.label}${S.showTime&&row.time?`<small>${row.time}</small>`:''}</div>`;if(row.merged){const c=getCell(row.key,0);for(let d=0;d<S.days;d++)html+=`<button type="button" class="edit-cell course" data-row="${row.key}" data-day="${d}" data-visible="${d===S.selectedDay}"><span><strong>${escapeHtml(c.subject||'點此輸入')}</strong></span></button>`}else{for(let d=0;d<S.days;d++){const c=getCell(row.key,d);const secondary=[c.teacher,c.room].filter(Boolean).join('・');html+=`<button type="button" class="edit-cell course" data-row="${row.key}" data-day="${d}" data-visible="${d===S.selectedDay}"><span><strong>${escapeHtml(c.subject||'＋')}</strong>${secondary?`<small>${escapeHtml(secondary)}</small>`:''}</span></button>`}}html+='</div>'}html+='</div>';$('#courseEditor').innerHTML=html;renderDayTabs()}
function escapeHtml(v){return String(v).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}

function renderFonts(){$('#fontCount').textContent=`${FONTS.length} 款固定字體`;$('#fontGrid').innerHTML=FONTS.map((f,i)=>`<button type="button" data-font="${i}" class="${S.font===i?'active':''}" style="font-family:${f.family}">${f.name}</button>`).join('')}
function renderBackgrounds(){const list=S.backgroundMode==='template'?TEMPLATES:SOLIDS;$('#solidOptions').hidden=S.backgroundMode!=='solid';$$('[data-bg-mode]').forEach(b=>b.classList.toggle('active',b.dataset.bgMode===S.backgroundMode));$('#backgroundGrid').innerHTML=list.map(v=>{const active=S.backgroundMode==='template'?S.template===v[0]:S.solid===v[0];if(S.backgroundMode==='template')return `<button type="button" data-bg="${v[0]}" class="${active?'active':''}"><span class="swatch"><img loading="lazy" src="../assets/timetable/templates/${v[2]}" alt=""></span>${v[1]}</button>`;const bg=S.gradient?`linear-gradient(135deg,${v[2]},#fff7fb)`:v[2];return `<button type="button" data-bg="${v[0]}" class="${active?'active':''}"><span class="swatch" style="background:${bg}"></span>${v[1]}</button>`}).join('')}

function loadImage(src){if(S.images.has(src))return Promise.resolve(S.images.get(src));return new Promise((resolve,reject)=>{const im=new Image;im.onload=()=>{S.images.set(src,im);resolve(im)};im.onerror=reject;im.src=src})}
function roundedRect(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
function drawText(text,x,y,size,weight='700',color=S.textColor,align='center',maxWidth){if(!text)return;ctx.save();ctx.font=`${weight} ${size}px ${FONTS[S.font].family}`;ctx.fillStyle=color;ctx.textAlign=align;ctx.textBaseline='middle';ctx.lineJoin='round';ctx.strokeStyle='rgba(255,255,255,.92)';ctx.lineWidth=Math.max(2,size*.08);ctx.strokeText(text,x,y,maxWidth);ctx.fillText(text,x,y,maxWidth);ctx.restore()}
function fitText(text,maxWidth,startSize,minSize=20){let s=startSize;ctx.font=`800 ${s}px ${FONTS[S.font].family}`;while(s>minSize&&ctx.measureText(text).width>maxWidth){s-=2;ctx.font=`800 ${s}px ${FONTS[S.font].family}`}return s}
function drawCoverImage(im,w,h){const scale=Math.max(w/im.width,h/im.height),sw=w/scale,sh=h/scale,sx=(im.width-sw)/2,sy=(im.height-sh)/2;ctx.drawImage(im,sx,sy,sw,sh,0,0,w,h)}
async function drawBackground(w,h){if(S.backgroundMode==='template'){const item=TEMPLATES.find(v=>v[0]===S.template);try{const im=await loadImage(`../assets/timetable/templates/${item[2]}`);drawCoverImage(im,w,h)}catch{ctx.fillStyle='#fff8f3';ctx.fillRect(0,0,w,h)}}else{const c=SOLIDS.find(v=>v[0]===S.solid)?.[2]||'#fbdce8';if(S.gradient){const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,c);g.addColorStop(1,'#fff9fc');ctx.fillStyle=g}else ctx.fillStyle=c;ctx.fillRect(0,0,w,h)}}
async function drawCanvas(){await document.fonts.ready;const format=S.format==='a4'?{w:3508,h:2480,label:'A4 橫式'}:{w:1800,h:1200,label:'4×6 橫式'};canvas.width=format.w;canvas.height=format.h;await drawBackground(format.w,format.h);const W=format.w,H=format.h,scale=H/2480;
const marginX=(S.format==='a4'?360:160),top=(S.format==='a4'?300:145),bottom=(S.format==='a4'?250:110);const x=marginX,y=top,w=W-marginX*2,h=H-top-bottom;
ctx.save();roundedRect(ctx,x,y,w,h,38*scale);ctx.fillStyle='rgba(255,255,255,.10)';ctx.fill();ctx.strokeStyle='rgba(126,92,111,.30)';ctx.lineWidth=Math.max(2,5*scale);ctx.stroke();ctx.restore();
const titleSize=fitText($('#titleInput').value||'我的課表',w*.62,(S.format==='a4'?92:47)*S.fontScale,28);drawText($('#titleInput').value||'我的課表',W/2,y-(S.format==='a4'?125:57),titleSize,'900');
const info=[($('#schoolInput').value||'').trim(),($('#termInput').value||'').trim(),[($('#nameInput').value||'').trim(),($('#classInput').value||'').trim(),($('#teacherInput').value||'').trim()?`導師：${$('#teacherInput').value.trim()}`:''].filter(Boolean).join('　')].filter(Boolean);drawText(info.join('　｜　'),W/2,y-(S.format==='a4'?52:25),(S.format==='a4'?34:18)*S.fontScale,'700','#6e5964','center',w*.9);
const rows=rowDefs(),labelW=w*(S.format==='a4'?.145:.16),colW=(w-labelW)/S.days,rowH=h/(rows.length+1),headerH=rowH;ctx.save();roundedRect(ctx,x,y,w,h,34*scale);ctx.clip();
// 課表格子保持透明，只以格線與文字呈現，讓背景模板完整可見。
ctx.strokeStyle='rgba(105,80,94,.32)';ctx.lineWidth=Math.max(1,3*scale);for(let d=0;d<=S.days;d++){const xx=x+labelW+d*colW;ctx.beginPath();ctx.moveTo(xx,y);ctx.lineTo(xx,y+h);ctx.stroke()}ctx.beginPath();ctx.moveTo(x,y+headerH);ctx.lineTo(x+w,y+headerH);ctx.stroke();
drawText('節次／星期',x+labelW/2,y+headerH/2,(S.format==='a4'?31:16)*S.fontScale,'800');for(let d=0;d<S.days;d++)drawText(DAY_NAMES[d],x+labelW+colW*(d+.5),y+headerH/2,(S.format==='a4'?35:18)*S.fontScale,'900');
rows.forEach((row,r)=>{const yy=y+headerH+r*rowH;ctx.beginPath();ctx.moveTo(x,yy+rowH);ctx.lineTo(x+w,yy+rowH);ctx.stroke();drawText(row.label,x+labelW/2,yy+rowH*(S.showTime&&row.time?.44:.5),(S.format==='a4'?31:15)*S.fontScale,'900');if(S.showTime&&row.time)drawText(row.time,x+labelW/2,yy+rowH*.72,(S.format==='a4'?22:11)*S.fontScale,'700','#75636c');
if(row.merged){const c=getCell(row.key,0),cx=x+labelW+(w-labelW)/2;drawText(c.subject||'午休',cx,yy+rowH/2,(S.format==='a4'?32:16)*S.fontScale,'800','#705a64','center',w-labelW-20)}else for(let d=0;d<S.days;d++){const c=getCell(row.key,d),cx=x+labelW+colW*(d+.5);if(c.subject){ctx.save();roundedRect(ctx,x+labelW+d*colW+8*scale,yy+8*scale,colW-16*scale,rowH-16*scale,16*scale);ctx.fillStyle=subjectColor(c.subject);ctx.fill();ctx.restore();const main=(S.format==='a4'?32:16)*S.fontScale,sz=fitText(c.subject,colW*.85,main,10);drawText(c.subject,cx,yy+rowH*(c.teacher||c.room?.42:.5),sz,'900','#4e3d46','center',colW*.86);const sec=[c.teacher,c.room].filter(Boolean).join('・');if(sec)drawText(sec,cx,yy+rowH*.72,(S.format==='a4'?20:10)*S.fontScale,'700','#735f69','center',colW*.88)}}});ctx.restore();
ctx.save();roundedRect(ctx,x,y,w,h,34*scale);ctx.strokeStyle='rgba(105,80,94,.38)';ctx.lineWidth=Math.max(2,5*scale);ctx.stroke();ctx.restore();drawText('© 2026 Feixin Kids · Design · Download · Print',W/2,H-(S.format==='a4'?70:32),(S.format==='a4'?26:13),'500','#8e7b84');$('#meta').textContent=format.label;updateMobilePreview();persistProfile()}

function openCell(row,day){S.editingKey={row,day};const c=getCell(row,day);$('#cellModalTitle').textContent=`${DAY_NAMES[day]}・${rowDefs().find(r=>r.key===row)?.label||''}`;$('#cellSubject').value=c.subject||'';$('#cellTeacher').value=c.teacher||'';$('#cellRoom').value=c.room||'';const simple=row==='clothing'||row==='lunch';$('#toggleMoreFields').hidden=simple;$('#cellMoreFields').hidden=simple||!(c.teacher||c.room);$('#cellModal').hidden=false;setTimeout(()=>$('#cellSubject').focus(),50)}
function closeCell(){$('#cellModal').hidden=true;S.editingKey=null}
function renderTimes(){const rows=S.times.slice(0,S.periodCount);$('#timeEditorList').innerHTML=rows.map((t,i)=>`<div class="time-row"><strong>${t[0]}</strong><input type="time" data-time-index="${i}" data-time-part="1" value="${t[1]}"><input type="time" data-time-index="${i}" data-time-part="2" value="${t[2]}"></div>`).join('')}
function fillSample(){const sample=[['國語','數學','英語','國語','生活課程','自然','閱讀','綜合活動','閱讀'],['數學','國語','自然','英語','國語','音樂','美勞','體育','閱讀'],['體育','音樂','國語','美勞','自然','社團','健康','閱讀','綜合活動'],['國語','數學','英語','自然','班會','才藝','閱讀','生活課程','健康'],['英語','自然','數學','體育','本土語','戶外','音樂','閱讀','綜合活動']];S.courses={};S.clothingData=Array(7).fill('');for(let d=0;d<Math.min(S.days,5);d++){S.clothingData[d]=d===1||d===3?'運動服':'制服';for(let i=0;i<S.periodCount;i++){const shouldFill=d===1||i<4;if(shouldFill)setCell(`p${i}`,d,{subject:sample[d][i%sample[d].length],teacher:'',room:''})}}if(S.morning)for(let d=0;d<Math.min(S.days,5);d++)setCell('morning',d,{subject:d===2?'升旗':'晨光閱讀'});S.courses.lunch={subject:'午休'};renderCourseEditor();drawCanvas()}
function persistProfile(){window.FeixinSharedData?.write({chineseName:$('#nameInput').value,englishName:'',className:$('#classInput').value})}
function download(url,name){const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove()}
function filename(ext){return `Feixin-Kids-V6.0-課表-${S.format==='a4'?'A4橫式':'4x6橫式'}.${ext}`}

$$('[data-days]').forEach(b=>b.addEventListener('click',()=>{$$('[data-days]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.days=+b.dataset.days;if(S.selectedDay>=S.days)S.selectedDay=0;renderCourseEditor();drawCanvas()}));
$('#periodCount').addEventListener('change',e=>{S.periodCount=+e.target.value;renderCourseEditor();drawCanvas()});
[['clothingToggle','clothing'],['morningToggle','morning'],['lunchToggle','lunch'],['afterToggle','after'],['timeToggle','showTime']].forEach(([id,key])=>$('#'+id).addEventListener('change',e=>{S[key]=e.target.checked;renderCourseEditor();drawCanvas()}));
$('#courseEditor').addEventListener('click',e=>{const b=e.target.closest('[data-row]');if(b)openCell(b.dataset.row,+b.dataset.day)});$('#dayTabs').addEventListener('click',e=>{const b=e.target.closest('[data-mobile-day]');if(!b)return;S.selectedDay=+b.dataset.mobileDay;renderCourseEditor()});
$('#saveCellBtn').addEventListener('click',()=>{if(!S.editingKey)return;setCell(S.editingKey.row,S.editingKey.day,{subject:$('#cellSubject').value.trim(),teacher:$('#cellTeacher').value.trim(),room:$('#cellRoom').value.trim()});closeCell();renderCourseEditor();drawCanvas()});$('#deleteCellBtn').addEventListener('click',()=>{if(!S.editingKey)return;setCell(S.editingKey.row,S.editingKey.day,{subject:'',teacher:'',room:''});closeCell();renderCourseEditor();drawCanvas()});$('#closeCellModal').onclick=closeCell;$('#cellModal').addEventListener('click',e=>{if(e.target===$('#cellModal'))closeCell()});$('#toggleMoreFields').onclick=()=>{$('#cellMoreFields').hidden=!$('#cellMoreFields').hidden};
$('#editTimesBtn').onclick=()=>{renderTimes();$('#timeModal').hidden=false};$('#closeTimeModal').onclick=()=>$('#timeModal').hidden=true;$('#saveTimesBtn').onclick=()=>{$$('#timeEditorList input').forEach(i=>S.times[+i.dataset.timeIndex][+i.dataset.timePart]=i.value);$('#timeModal').hidden=true;renderCourseEditor();drawCanvas()};
$('#sampleBtn').onclick=fillSample;$('#clearCoursesBtn').onclick=()=>{if(!confirm('確定要清空所有課程與服裝嗎？'))return;S.courses={};S.clothingData=Array(7).fill('');renderCourseEditor();drawCanvas()};
$$('#titleInput,#nameInput,#classInput,#schoolInput,#termInput,#teacherInput').forEach(i=>i.addEventListener('input',drawCanvas));
$('#fontGrid').addEventListener('click',e=>{const b=e.target.closest('[data-font]');if(!b)return;S.font=+b.dataset.font;renderFonts();drawCanvas()});$('#textColor').addEventListener('input',e=>{S.textColor=e.target.value;drawCanvas()});$('#fontSizeRange').addEventListener('input',e=>{S.fontScale=+e.target.value/100;$('#fontSizeValue').textContent=e.target.value+'%';drawCanvas()});
$$('[data-bg-mode]').forEach(b=>b.onclick=()=>{S.backgroundMode=b.dataset.bgMode;renderBackgrounds();drawCanvas()});$('#backgroundGrid').addEventListener('click',e=>{const b=e.target.closest('[data-bg]');if(!b)return;if(S.backgroundMode==='template')S.template=b.dataset.bg;else S.solid=b.dataset.bg;renderBackgrounds();drawCanvas()});$('#gradientToggle').onchange=e=>{S.gradient=e.target.checked;renderBackgrounds();drawCanvas()};
$$('[data-format]').forEach(b=>b.onclick=()=>{$$('[data-format]').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.format=b.dataset.format;drawCanvas()});
$('#pngBtn').onclick=async()=>{await drawCanvas();download(canvas.toDataURL('image/png'),filename('png'))};$('#pdfBtn').onclick=async()=>{try{await drawCanvas();if(!window.jspdf?.jsPDF)throw new Error('PDF 元件載入失敗，請確認網路連線後重新整理。');const {jsPDF}=window.jspdf,p=new jsPDF({orientation:'landscape',unit:'mm',format:S.format==='a4'?'a4':[152.4,101.6],compress:true});const pw=S.format==='a4'?297:152.4,ph=S.format==='a4'?210:101.6;p.addImage(canvas.toDataURL('image/jpeg',.96),'JPEG',0,0,pw,ph,undefined,'FAST');p.save(filename('pdf'))}catch(err){alert(err.message)}};
$('#resetBtn').onclick=()=>{if(!confirm('確定要重新開始嗎？'))return;location.reload()};

const previewSection=$('.preview'),placeholder=document.createComment('preview-home'),modal=$('#mobilePreviewModal'),content=$('#mobilePreviewContent');function updateMobilePreview(){const c=$('#mobilePreviewCanvas'),m=c.getContext('2d');m.clearRect(0,0,c.width,c.height);m.fillStyle='#f4edf1';m.fillRect(0,0,c.width,c.height);const scale=Math.min(c.width/canvas.width,c.height/canvas.height),dw=canvas.width*scale,dh=canvas.height*scale;m.drawImage(canvas,(c.width-dw)/2,(c.height-dh)/2,dw,dh)}function openPreview(){if(!placeholder.parentNode)previewSection.parentNode.insertBefore(placeholder,previewSection);content.appendChild(previewSection);modal.hidden=false;document.body.style.overflow='hidden'}function closePreview(){if(placeholder.parentNode){placeholder.parentNode.insertBefore(previewSection,placeholder);placeholder.remove()}modal.hidden=true;document.body.style.overflow=''}$('#mobilePreviewBtn').onclick=openPreview;$('#desktopPreviewBtn').onclick=openPreview;$('#closeMobilePreviewBtn').onclick=closePreview;modal.addEventListener('click',e=>{if(e.target===modal)closePreview()});

document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCell();$('#timeModal').hidden=true;if(!modal.hidden)closePreview()}});
const profile=window.FeixinSharedData?.read();if(profile){$('#nameInput').value=profile.chineseName||'林小可';$('#classInput').value=profile.className||'一年1班'}
renderFonts();renderBackgrounds();renderCourseEditor();fillSample();
})();
